---
server:
  port: 8081

spring:
  profiles:
    active: dev
  rabbitmq:
    virtual-host: tweetme_dev
    port: 5672
    host: localhost
    username: admin
    password: 123

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    username: tweetme
    password: 123
    url: jdbc:postgresql://localhost:5433/tweetme
    platform: postgres

messaging:
  modifyQueue:
    name: "modifyQueue"